---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-{{ .Values.application.name }}-github-webhook
  namespace: {{ .Values.application.environments.cicd }}
spec:
  serviceAccountName: tekton-triggers-createwebhook
  taskRef:
    name: {{ .Values.application.name }}-create-webhook
  params:
  - name: GitHubOrg
    value: {{ .Values.pipeline.webhook.github.org }}
  - name: GitHubUser
    value: {{ .Values.pipeline.webhook.github.user }}
  - name: GitHubRepo
    value: {{ .Values.pipeline.webhook.github.repo }}
  - name: GitHubSecretName
    value: {{ .Values.pipeline.webhook.github.secret }}
  - name: GitHubAccessTokenKey
    value: password
  - name: GitHubSecretStringKey
    value: secret
  - name: ExternalDomain
    value: http://{{ .Values.application.name }}-trigger-{{ .Values.application.environments.cicd }}.{{ .Values.cluster }}
