---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.environments.cicd }}
spec:
  serviceAccountName: {{ .Values.pipeline.sa.triggers }}
  triggers:
    - name: cel-trig-with-canonical
      interceptors:
        - cel:
            filter: "header.canonical('X-GitHub-Event') == 'push'"
      bindings:
        - ref: {{ .Values.application.name }}-trigger-binding
      template:
        name: {{ .Values.application.name }}-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Values.application.name }}
  name: {{ .Values.application.name }}-trigger
  namespace: {{ .Values.application.environments.cicd }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.application.name }}
    weight: 100
  wildcardPolicy: None