---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.application.name }}-image-puller
  namespace: {{ .Values.application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.sa.default }}
  namespace: {{ .Values.application.environments.cicd }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.application.environments.development }}
  namespace: {{ .Values.application.environments.cicd }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.application.environments.production }}
  namespace: {{ .Values.application.environments.cicd }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.application.name }}-documentation
  namespace: {{ .Values.application.environments.cicd }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ .Values.application.name }}-development
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ .Values.application.environments.development }}/{{ .Values.application.name }}-development

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ .Values.application.name }}-documentation
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ .Values.application.environments.development }}/{{ .Values.application.name }}-documentation
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ .Values.application.name }}-production
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ .Values.application.environments.production }}/{{ .Values.application.name }}-production
