---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.application.name }}-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce