{{- if .Values.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: {{ include "argocd-operator.ns" . }}-argocd-application-controller
    app.kubernetes.io/part-of: {{ include "argocd-operator.ns" . }}
  name: {{ include "argocd-operator.ns" . }}-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argocd-operator.ns" . }}-argocd-application-controller
{{- if not .Values.namespaceRoleBinding.enabled }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-argocd-application-controller
  namespace: {{ include "argocd-operator.ns" . }}
{{- end }}
{{- end }}
