{{- if .Values.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: {{ include "argocd-operator.ns" . }}-argocd-application-controller
    app.kubernetes.io/part-of: {{ include "argocd-operator.ns" . }}
  name: {{ include "argocd-operator.ns" . }}-argocd-application-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
{{- end }}
