{{- if .Values.enabled }}
{{- if .Values.operator }}
{{- if .Values.operator.operatorgroup }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "argocd-operator.ns" . }}
  generateName: {{ include "argocd-operator.ns" . }}-
  namespace: {{ include "argocd-operator.ns" . }}
spec:
  targetNamespaces:
  - {{ include "argocd-operator.ns" . }}
{{- end }}
{{- end }}
{{- end }}
