{{- if .Values.persistence.enabled }}
apiVersion: apps/v1
kind: StatefulSet
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: static-site-{{ .Release.Name }}
  labels:
    app: static-site
    site: {{ .Release.Name }}
spec:
  # Correct replicas value will be patched later at the first poller (done as a Helm Chart post-install hook)
  replicas: 0
  {{- if .Values.persistence.enabled }}
  serviceName: static-site-{{ .Release.Name }}
  {{- else }}
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
  {{- end }}
  selector:
    matchLabels:
      app: static-site
      site: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: static-site
        site: {{ .Release.Name }}
        git_repo_hash: {{ .Values.repo.location | sha256sum | trunc 32 }}
        git_branch_hash: {{ .Values.repo.branch | sha256sum | trunc 32 }}
        git_revision: 'pending-init'
    spec:
      initContainers:
        - name: git
          image: jijiechen/alpine-curl-git:v2.24.1
          workingDir: /source
          command: ["/bin/sh"]
          args: ["/git/clone.sh"]
          volumeMounts:
            - name: website
              mountPath: /website
            - name: source
              mountPath: /source
            - name: config
              subPath: clone.sh
              mountPath: /git/clone.sh
          env:
            - name: GIT_REVISION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['git_revision']
          {{- if and .Values.repo.credential.username .Values.repo.credential.password }}
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: static-site-credential-{{ .Release.Name }}
                  key: gitPassword
          {{- end }}
      containers:
        - name: nginx
          image: nginx:{{ .Chart.AppVersion }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          command: ["/bin/sh"]
          args: ["-c", "mkdir -p /tmp/log/nginx/ && exec nginx -g 'daemon off;'"]
          resources:
            limits:
              cpu: 200m
              memory: "200Mi"
            requests:
              cpu: 50m
              memory: "100Mi"
          volumeMounts:
            - name: website
              mountPath: /usr/share/nginx/html
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: source
          emptyDir: {}
        {{- end }}
        - name: website
          emptyDir: {}
        - name: config
          configMap:
            name: static-site-{{ .Release.Name }}-config
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: source
        labels:
          app: static-site
          site: {{ .Release.Name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.storage.size | quote }}
        {{ include "tmpl.storageClass" . }}
  {{- end }}


{{- if and .Values.repo.credential.username .Values.repo.credential.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: static-site-credential-{{ .Release.Name }}
  labels:
    app: static-site
    site: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.repo.credential.username | b64enc | quote }}
  gitPassword: {{ .Values.repo.credential.password | b64enc | quote }}

{{- end }}
