{{- if .Values.enabled }}
{{ $labels := include "network-policy.labels" . }}
{{ $all_policies := .Values.policies }}
{{ if ne 0 (len .Values.multitenant_policies) }} 
{{ $all_policies = concat .Values.policies .Values.multitenant_policies }}
{{ end }}
{{- range $all_policies }}
{{- if . }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- $labels | nindent 4 }}
  name: {{ .name }}
spec: 
{{ toYaml .spec | indent 2 }}
{{ end }}
{{ end }}
{{ end }}
