cluster: apps.s45.core.rht-labs.com
registry:
  secret: 11009103-tekton-pipeline-pull-secret
application:
  name: do101
  runtime: nodejs:12
  environments:
    cicd: labs-ci-cd
    development: do101-development
    production: do101-production
pipeline:
  sa:
    default: pipeline
    triggers: do101-tekton-triggers-sa
  nexus:
    host: https://nexus-labs-ci-cd.apps.s45.core.rht-labs.com/repository/labs-npm
  build:
    s2i:
      context: weather

  webhook:
    github:
      org: mvmaestri
      user: mvmaestri
      repo: do101-apps
      secret: do101-github-webhook-secret
      key: do101-github-deploy-secret
