{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  labels:
    app: {{ .Values.appName }}
    credential.sync.jenkins.openshift.io: "true"
stringData:
  pact_broker_database_username: {{ .Values.secrets.values.pactBrokerDatabaseUsername }}
  pact_broker_database_password: {{ .Values.secrets.values.pactBrokerDatabasePassword }}
  pact_broker_admin: {{ .Values.secrets.values.pactBrokerBasicAuthUsername}}
  pact_broker_admin_password: {{ .Values.secrets.values.pactBrokerBasicAuthPassword }}
  pact_broker_user: {{ .Values.secrets.values.pactBrokerBasicAuthUsername }}
  pact_broker_user_password: {{ .Values.secrets.values.pactBrokerBasicAuthPassword }}
{{ end }}