---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ipa.fullname" . }}-anyuid
  labels:
    {{- include "ipa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name:  {{ include "ipa.fullname" . }}-user
  namespace: {{ include "ipa.namespace" . }}
