{{- if .Values.ocp_auth.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ipa.fullname" . }}-bind-password
  namespace: openshift-config
  labels:
    {{- include "ipa.labels" . | nindent 4 }}
stringData:
  bindPassword: {{ .Values.ocp_auth.bind_password }}
{{- end }}
