---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ipa.fullname" . }}-password
  labels:
    {{- include "ipa.labels" . | nindent 4 }}
stringData:
  admin.password: {{ .Values.admin_password }}
