apiVersion: v1
kind: Secret
metadata:
  {{ template "app.labels" }}
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{ .Values.db.name | default "gitea-db" | quote }}
stringData:
  database-name: {{ .Values.db.name | default "gitea-db" | quote }}
  database-password: {{ required "You MUST set the PostgreSQL password" .Values.db.password | quote }}
  database-user: {{ .Values.db.user | default "gitea" | quote }}
