apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The Gitea server's http port
  {{ template "app.labels" }}
  name: {{ template "app.name" }}
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ template "app.name" }}
    deploymentconfig: {{ template "app.name" }}
  sessionAffinity: None
  type: ClusterIP
