{{- range $key := .Values.sealed_secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  encryptedData:
    password: {{ .password }}
    username: {{ .username }}
  template:
    metadata:
      labels:
        credential.sync.jenkins.openshift.io: "true"
      name: {{ .name }}
    type: {{ .type | default "kubernetes.io/basic-auth" | quote }}
{{- end }}
