{{- range $key := .Values.source_secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    credential.sync.jenkins.openshift.io: "true"
{{- if .annotations }}
  annotations:
{{- toYaml .annotations | nindent 4 }}
{{- end}}
type: {{ .type | default "kubernetes.io/basic-auth" | quote }}
stringData:
  {{- if .token }}
  token: {{ .token | quote }}
  {{- else }}
  password: {{ .password | quote }}
  username:  {{ .username | quote }}
  {{- end }}
{{- end }}